%{
Copyright (c) 2012-2016, Ching-Yu Chen
// All rights reserved.
// 
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//     * Redistributions of source code or derivatives thereof must retain the 
//       above copyright notice, this list of conditions and the following
//       disclaimer.
//     * Redistributions in binary form, and any binary file that is compiled 
//       from a derivative of this source code, must reproduce the above 
//       copyright notice, this list of conditions and the following disclaimer 
//       in the documentation and/or other materials provided with the 
//       distribution.
//     * Any publication, presentation, or other publicly or privately 
//       presented work having made use of or benefited from this software or 
//       derivatives thereof must explicitly name Kale J. Franz in a section 
//       dedicated to acknowledgements or name Kale J. Franz as a co-author 
//       of the work.
//     * Any use of this software that directly or indirectly contributes to 
//       work or a product for which the user is or will be remunerated must be 
//       further licensed through the Princeton Univeristy Office of Technology 
//       Licensing and the Princeton Univeristy Mid-Infrared Photonics Lab led 
//       by Professor Claire Gmachl prior to the transaction of said 
//       remuneration.  
// 
// THIS SOFTWARE IS PROVIDED BY Ching-Yu Chen ''AS IS'' AND ANY
// EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL Ching-Yu Chen BE LIABLE FOR ANY
// DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
// (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
// LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
// ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
%}
%{
* The part same as nTimeEvolution.m
 The program calculate the time evolution of the electron distribution on
 each level with the given time step [ps], end time [ps], rate equation 
 coeffiecient and initial conditions.  
 The actual time evoltion would be calculated in (0.1 * dt) time 
 step, but save in dt time step.

* Two interacting stimulated transition states
In addition to consider non-radiative transitions to calculate the s.s.
electron distribution, here in the pogram,
    - The main two stimulated transitions in active region are considered.
    - Flux is also calculated.
As the stimulated transition depends on the photon flux inside the cavity, 
the stimulated transitios effect starts growing when the photon flux 
generated by the spontaneus emission build up. Therefore, initial condition
of the rate equation coefficient would base on the non-radiatve transition
and zero contribution by stimulated emission. Every certain time evolution,
the rate equation coefficient need to be updated due to the built-up
stimluated transition rate. Repeating time evoluation calculation until the
system reaches the steady state.

Given initialize reqnc(0), nIC,
1. use n(t) and reqnc(t) to calculate n(t + dt), 
2. use n(t) to calculate flux(t + dt)
3. use flux(t) to calculate stimulated transition coefficient cStim(t + dt) 
4. calculate reqnc(t + dt) = reqnc(t) - cStim(t) + cStim(t + dt) 
Repeat until reach the s.s.


%}

function [nTE, nTEPer, nss, nssSysStates, nsDiff] = nTimeEvolutionStim(upIn, lowIn, dIn, dt, tEnd, reqnC, nIC, numSysState, periIn, nonPeriIn, dpUL, dpLD, modeCon, Lp, waveLen, broadenUL, broadenLD, alphaW, alphaM, r1, r2)
    tEnd0 = tEnd;
    tEnd = tEnd / dt;  % change the tEnd unit from [ps] to number of time step
    dt = dt * 1.0e-12 * 0.1; % unit s
    dimen = size(reqnC, 1);
    nssSysStates(numSysState) = 0;
    nss(dimen) = 0;
    nt = nIC;
    ns = sum(nt);  % total doped sheet density
    
    Lp = Lp * 1.0e-8; % period length [cm]
    c0 = 3 * 1.0e10; % speed of light [cm/s]
    neff = 3.4; % effective refractive index
    vGroup = c0 / neff; % group velocity [cm/s]
    crossUL = (4 * 3.14 * 1.6 / 8.85 / neff) * 1.0e-14 * (dpUL * dpUL / waveLen / broadenUL) % [cm^2]
    crossLD = crossUL * ((dpLD * dpLD) / (dpUL * dpUL)) * (broadenUL / broadenLD) % [cm^2]
    factorUL = vGroup * modeCon * crossUL / Lp; % [cm^2 / s]
    factorLD = factorUL / crossUL  * crossLD; % [cm^2 / s]
    wSponUL = (8 * 3.14 * 3.14 / 3 * 1.6 * 1.6 / 1.05 / 8.85) * 1.0e6 * (neff * dpUL * dpUL / (waveLen * waveLen * waveLen)) % [1 / s]
    wSponLD = wSponUL * (dpLD * dpLD) / (dpUL * dpUL)  % [1 / s]
    sponFacUL = vGroup * wSponUL / Lp; % [1 / s^2]
    sponFacLD = vGroup * wSponLD / Lp; % [1 / s^2]
    tauPhInvers = vGroup * (alphaW + alphaM) * 1; % photon lifetime [1/s]
    cStim = [0, 0, 0, 0];
    fluxUL = 0.0;
    fluxLD = 0.0;
    
    nU = nt(upIn)
    nL = nt(lowIn)
    nD = nt(dIn)
    
    nt = nt';
    for t = 1 : tEnd   
        timePlot(t) = t * dt * (1.0e13);
        % flux(t+dt) cal
        [deltaFluxUL, stimUL(t), stimAUL(t), lossUL(t), sponUL(t)] = dfluxCal(fluxUL, fluxLD, r1, r2, dt, factorUL, factorLD, sponFacUL, tauPhInvers, nU, nL, nD);
        [deltaFluxLD, stimLD(t), stimALD(t), lossLD(t), sponLD(t)] = dfluxCal(fluxLD, fluxUL, r2, r1, dt, factorLD, factorUL, sponFacLD, tauPhInvers, nL, nD, nL);
        fluxUL = fluxUL + deltaFluxUL;
        fluxLD = fluxLD + deltaFluxLD;
        fluxSaveUL(t) = fluxUL;
        fluxSaveLD(t) = fluxLD;   
        
        % reqnC(t + dt) cal, reqnc(t + dt) = reqnc(t) - cStim(t) + cStim(t + dt) 
        % reqnc(t) - cStim(t)
        reqnC = stimuTrans(reqnC, upIn, lowIn, dIn, -1 .* cStim);
        % calculate cStim(t + dt)
        cStim(1) = (fluxUL * r1 + fluxLD * r2) * crossUL * modeCon; % CintLU, CintUL, -1 * CintUU
        cStim(2) = (fluxUL * r1 + fluxLD * r2) * crossLD * modeCon; % CintDL, CintLD, -1 * CintDD 
        cStim(3) = fluxUL * (1 - r1) * crossUL * modeCon;  % CnonLU, CnonUL, -1 * CnonUU
        cStim(4) = fluxLD * (1 - r2) * crossLD * modeCon; % CnonDL, CnonLD, -1 * CnonDD
        % reqC(t+dt) = (reqnc(t) - cStim(t)) +  cStim(t + dt)
        reqnC = stimuTrans(reqnC, upIn, lowIn, dIn, cStim);
        
        % n(t+dt) cal
        nt = ((reqnC * dt + eye(dimen)) ^ 10) * nt; % n(t + dt * 10) = ((I + [dn/dt] * dt) ^ 10) * n(t)
        nTE(t, :) = nt;
        nsDiff(t) = sum(nt) - ns; % The deviation of ns after dt of evolution
        nt = nt - (nsDiff(t) / dimen); % Calibrate n(t) by subtracting the deviation of the (sheet denisty / states)
        nU = nt(upIn);
        nL = nt(lowIn);
        nD = nt(dIn);
    end
    nTEPer = nTE ./ ns;

    for i = 1 : dimen
        nssSysStates(periIn(i)) = nTE(tEnd, i);
        nssSysStates(nonPeriIn(i)) = nTE(tEnd, i);
        nss(i) = nTE(tEnd, i);
    end
    fluxSaveUL = fluxSaveUL';
    fluxSaveLD = fluxSaveLD';
    stimUL = stimUL';
    stimAUL = stimAUL';
    lossUL = lossUL';
    sponUL = sponUL';
    stimLD = stimLD';
    stimALD = stimALD';
    lossLD = lossLD';
    sponLD = sponLD';

    sLoss = num2str(tauPhInvers / vGroup);
    % sTemp = num2str(80);
    % sBias = num2str(49.5);
    % sParameters = strcat('  (Loss ', sLoss, ' cm-1, ', sTemp, ' K, bias ', sBias, ' kV/cm)');
    sParameters = strcat({' '},{'(Loss'}, {' '}, sLoss, {' '}, {'cm-1)'});
    
    figure
    plot(timePlot, nTE(:, upIn), timePlot, nTE(:, lowIn), timePlot,  nTE(:, dIn), 'LineWidth', 2);
    sTitle = strcat('Time Evolution', sParameters);
    title(sTitle, 'FontSize', 20);
    set(gca, 'FontSize', 18,'LineWidth', 1.5);
    xlabel('t (ps)', 'FontSize', 20) % x-axis label
    ylabel('ni (1/cm2)', 'FontSize', 20) % y-axis label
    legend('nU','nL','nD');
    saveas(gcf, 'timeEvolution.fig');
    saveas(gcf, 'timeEvolution.tif');
    
    figure
    endPoint = size(timePlot, 2) * 0.1;
    plot(timePlot(1 : endPoint), nTE(1 : endPoint, upIn), timePlot(1 : endPoint), nTE(1 : endPoint, lowIn), timePlot(1 : endPoint),  nTE(1 : endPoint, dIn), 'LineWidth', 2);
    sTitle = strcat('Time Evolution (shorter range)', sParameters);
    title(sTitle, 'FontSize', 20);
    set(gca, 'FontSize', 18, 'LineWidth', 1.5);
    xlabel('t (ps)', 'FontSize', 20) % x-axis label
    ylabel('ni (1/cm2)', 'FontSize', 20) % y-axis label
    legend('nU','nL','nD');
    saveas(gcf, 'timeEvolutionShorter.fig');
    saveas(gcf, 'timeEvolutionShorter.tif');
    
    figure
    plot(timePlot(1 : endPoint), sponUL(1 : endPoint), timePlot(1 : endPoint), sponLD(1 : endPoint), 'LineWidth', 2);
    sTitle = strcat('Spontaneous Emission (shorter range)', sParameters);
    title(sTitle, 'FontSize', 20);
    set(gca, 'FontSize', 18, 'LineWidth', 1.5);
    xlabel('t (ps)', 'FontSize', 20) % x-axis label
    ylabel('dflux / dt (#/(cm2*s2))', 'FontSize', 20) % y-axis label
    legend('sponUL','sponLD');
    saveas(gcf, 'sponShorter.fig');
    saveas(gcf, 'sponShorter.tif');
    
    figure
    semilogy(timePlot, fluxSaveUL, timePlot, fluxSaveLD, 'LineWidth', 2);
    axis([0, tEnd0, 1.0e19, 1.0e40]);
    % plot(timePlot, fluxSaveUL, timePlot, fluxSaveLD, 'LineWidth', 2);
    sTitle = strcat('Flux', sParameters);
    title(sTitle, 'FontSize', 20);
    set(gca, 'FontSize', 18, 'LineWidth', 1.5);
    xlabel('t (ps)', 'FontSize', 20) % x-axis label
    ylabel('flux (#/(cm2*s))', 'FontSize', 20) % y-axis label
    legend('fluxUL','fluxLD');
    saveas(gcf, 'fluxLog.fig');
    saveas(gcf, 'fluxLog.tif');
    
    figure
    plot(timePlot, fluxSaveUL, timePlot, fluxSaveLD, 'LineWidth', 2);
    sTitle = strcat('Flux', sParameters);
    title(sTitle, 'FontSize', 20);
    set(gca, 'FontSize', 18, 'LineWidth', 1.5);
    xlabel('t (ps)', 'FontSize', 20) % x-axis label
    ylabel('flux (#/(cm2*s))', 'FontSize', 20) % y-axis label
    legend('fluxUL','fluxLD');
    saveas(gcf, 'flux.fig');
    saveas(gcf, 'flux.tif');
    
    figure
    plot(timePlot, stimUL, timePlot, stimAUL, 'LineWidth', 2);
    sTitle = strcat('Stimulated Flux UL', sParameters);
    title(sTitle, 'FontSize', 20);
    set(gca, 'FontSize', 18, 'LineWidth', 1.5);
    xlabel('t (ps)', 'FontSize', 20) % x-axis label
    ylabel('dflux/dt (#/(cm2*s2))', 'FontSize', 20) % y-axis label
    legend('stimUL Own','stimUL Inter');
    saveas(gcf, 'stimdFluxUL.fig');
    saveas(gcf, 'stimdFluxUL.tif');
    
    
    figure
    plot(timePlot, stimLD, timePlot, stimALD, 'LineWidth', 2);
    set(gca, 'FontSize', 18, 'LineWidth', 1.5);
    sTitle = strcat('Stimulated Flux LD', sParameters);
    title(sTitle, 'FontSize', 20);
    xlabel('t (ps)', 'FontSize', 20) % x-axis label
    ylabel('dflux/dt (#/(cm2*s2))', 'FontSize', 20) % y-axis label
    legend('stimLD Own','stimLD Inter');
    saveas(gcf, 'stimdFluxLD.fig');
    saveas(gcf, 'stimdFluxLD.tif');
    
    figure
    plot(timePlot, sponUL, timePlot, sponLD, 'LineWidth', 2);
    set(gca, 'FontSize', 18, 'LineWidth', 1.5);
    sTitle = strcat('Spontaneous Emission', sParameters);
    title(sTitle, 'FontSize', 20);
    xlabel('t (ps)', 'FontSize', 20) % x-axis label
    ylabel('dflux/dt (#/(cm2*s2))', 'FontSize', 20) % y-axis label
    legend('sponUL', 'sponLD');
    saveas(gcf, 'spondFlux.fig');
    saveas(gcf, 'spondFlux.tif');
    
    
    figure
    plot(timePlot, stimUL - stimAUL, '--', timePlot, stimLD - stimALD, '--', timePlot, sponUL,':', timePlot, sponLD, ':', 'LineWidth', 2);
    sTitle = strcat('dFlux/dt', sParameters);
    title(sTitle, 'FontSize', 20);
    set(gca, 'FontSize', 18, 'LineWidth', 1.5);
    xlabel('t (ps)', 'FontSize', 20) % x-axis label
    ylabel('dflux/dt (#/(cm2*s2))', 'FontSize', 20) % y-axis label
    legend('stimTransUL', 'stimTransLD', 'sponUL', 'sponLD');
    saveas(gcf, 'dFluxdtStimSpon.fig');
    saveas(gcf, 'dFluxdtStimSpon.tif');
    
    figure
    semilogy(timePlot, stimUL - stimAUL, '--', timePlot, stimLD - stimALD, '--', timePlot, sponUL,':', timePlot, sponLD, ':', 'LineWidth', 2);
    axis([0, tEnd0, 1.0e26, 1.0e40]);
    sTitle = strcat('dFlux/dt', sParameters);
    title(sTitle, 'FontSize', 20);
    set(gca, 'FontSize', 18, 'LineWidth', 1.5);
    xlabel('t (ps)', 'FontSize', 20) % x-axis label
    ylabel('dflux/dt (#/(cm2*s2))', 'FontSize', 20) % y-axis label
    legend('stimTransUL', 'stimTransLD', 'sponUL', 'sponLD');
    saveas(gcf, 'dFluxdtLogStimSpon.fig');
    saveas(gcf, 'dFluxdtLogStimSpon.tif');
    
    
    save('fluxSaveUL.txt','fluxSaveUL','-ascii');
    save('fluxSaveLD.txt','fluxSaveLD','-ascii');
    save('stimUL.txt','stimUL','-ascii');
    save('stimAUL.txt','stimAUL','-ascii');
    save('lossUL.txt','lossUL','-ascii');
    save('sponUL.txt','sponUL','-ascii');
    save('stimLD.txt','stimLD','-ascii');
    save('stimALD.txt','stimALD','-ascii');
    save('lossLD.txt','lossLD','-ascii');
    save('sponLD.txt','sponLD','-ascii');
end